name: "Setup Repo and R"
description: "Clones the repo, installs R, and sets up dependencies"
inputs:
  r-version:
    description: "The version of R to use"
    default: "release"
  extra-packages:
    description: "Additional R packages to install"
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version }}
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: ${{ inputs.extra-packages }}
