image: rocker/tidyverse

stages:
  - test
  - build

default:
  cache: &global_cache
    key: r-pgk-cache-$CI_COMMIT_SHA
    paths:
      - .R_pkgs/
    policy: pull

setup:
  stage: .pre
  cache:
    <<: *global_cache
    policy: push
  script:
    - echo 'R_LIBS_USER=.R_pkgs/' > ~/.Renviron
    - mkdir .R_pkgs
    - Rscript -e 'devtools::install_github("flowr-analysis/flowr-r-adapter")'
    - Rscript -e 'devtools::install_dev_deps()'
    - ls -la .R_pkgs

check:
  stage: test
  cache:
    <<: *global_cache
  script:
    - ls -la .R_pkgs
    - Rscript -e 'devtools::check(error_on= "error")'

lint:
  stage: test
  cache:
    <<: *global_cache
  variables:
    LINTR_ERROR_ON_LINT: false
  script:
    - ls -la .R_pkgs
    - Rscript -e 'install.packages("lintr")'
    - Rscript -e 'lintr::lint_package()'

# TODO: Uncomment once we have tests
# test:
#   stage: test
#   cache:
#     <<: *global_cache
#   script:
#     - Rscript -e '.libPaths("../R") ; devtools::test()'

build:
  stage: build
  cache:
    <<: *global_cache
  script:
    - ls -la .R_pkgs
    - Rscript -e 'devtools::build()'
