image: rocker/tidyverse

stages:
  - test
  - build

setup:
  stage: .pre
  script:
    - Rscript -e 'devtools::install_dev_deps()'

check:
  stage: test
  script:
    - Rscript -e 'devtools::check(error_on= "error")'

lint:
  stage: test
  variables:
    LINTR_ERROR_ON_LINT: true
  script:
    - Rscript -e 'lintr::lint_package()'

# TODO: Uncomment once we have tests
# test:
#   stage: test
#   script:
#     - Rscript -e 'devtools::test()'

build:
  stage: build
  script:
    - Rscript -e 'devtools::build()'
