image: rocker/tidyverse

stages:
  - test
  - build

default:
  cache: &global_cache
    key: r-pgk-cache
    paths:
      - "../R"
    policy: pull

setup:
  stage: .pre
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - mkdir -p "../R"
    - echo '.libPaths("../R")' > ~/.Rprofile
    - Rscript -e '.libPaths("../R") ; install.packages("lintr")'
    - Rscript -e '.libPaths("../R") ; devtools::install_github("flowr-analysis/flowr-r-adapter")'
    - Rscript -e '.libPaths("../R") ; devtools::install_dev_deps()'

check:
  stage: test
  cache:
    <<: *global_cache
  script:
    - Rscript -e '.libPaths("../R") ; devtools::check(error_on= "error")'

lint:
  stage: test
  cache:
    <<: *global_cache
  variables:
    LINTR_ERROR_ON_LINT: true
  script:
    - Rscript -e '.libPaths("../R") ; lintr::lint_package()'

# TODO: Uncomment once we have tests
# test:
#   stage: test
#   cache:
#     <<: *global_cache
#   script:
#     - Rscript -e '.libPaths("../R") ; devtools::test()'

build:
  stage: build
  cache:
    <<: *global_cache
  script:
    - Rscript -e '.libPaths("../R") ; devtools::build()'
