image: rocker/tidyverse

stages:
  - test
  - build

default:
  cache: &global_cache
    key:
      files:
        - DESCRIPTION
    paths:
      - $CI_PROJECT_DIR/.R_pkgs/
    policy: pull

setup:
  stage: .pre
  cache:
    <<: *global_cache
    policy: pull-push
  script:
    - echo '.libPaths("$CI_PROJECT_DIR/.R_pkgs")' > $CI_PROJECT_DIR/.Rprofile
    - mkdir .R_pkgs
    - Rscript -e 'devtools::install_github("flowr-analysis/flowr-r-adapter")'
    - Rscript -e 'devtools::install_dev_deps()'

check:
  stage: test
  cache:
    <<: *global_cache
  script:
    - Rscript -e 'devtools::check(error_on= "error")'

lint:
  stage: test
  cache:
    <<: *global_cache
  variables:
    LINTR_ERROR_ON_LINT: false
  script:
    - Rscript -e 'install.packages("lintr")'
    - Rscript -e 'lintr::lint_package()'

# TODO: Uncomment once we have tests
# test:
#   stage: test
#   cache:
#     <<: *global_cache
#   script:
#     - Rscript -e '.libPaths("../R") ; devtools::test()'

build:
  stage: build
  cache:
    <<: *global_cache
  script:
    - Rscript -e 'devtools::build()'
