on:
  push:
    paths: ["R/**"]

permissions: read-all

jobs:
  document:
    runs-on: ubuntu-latest
    name: Document package
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Setup repo and R
        uses: flowr-analysis/slicing-coverage-r-package/.github/actions/setup@main
        with:
          extra-packages: |
            any::roxygen2
      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}
      - name: Commit and push
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "Update documentation" || echo "No changes to commit"
          git pull --ff-only
          git push origin
