on: push

permissions: read-all

jobs:
  check-and-build:
    runs-on: ${{ matrix.config.os }}
    name: Check and build on ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest, r: "release" }
          - { os: windows-latest, r: "release" }
          - { os: ubuntu-latest, r: "release" }
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
      - name: Build
        id: build
        run: |
          path <- devtools::build()
          cat("pkg-build-path=", path, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
        shell: Rscript {0}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}-r{2}-pkg', runner.os, runner.arch, matrix.config.r) }}
          path: ${{ steps.build.outputs.pkg-build-path }}

  lint:
    runs-on: ubuntu-latest
    name: Lint package
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lintr
            local::.
          needs: lint
      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
